import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/providers";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Pass Case",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	console.log("sans", geistSans.variable);
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.className} antialiased font-medium`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
